# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-27 03:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BarCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bar_code', models.IntegerField(unique=True, verbose_name='图书条码')),
            ],
        ),
        migrations.AlterField(
            model_name='book',
            name='CLC',
            field=models.CharField(max_length=200, unique=True, verbose_name='分类号'),
        ),
        migrations.AlterField(
            model_name='book',
            name='ISBN',
            field=models.IntegerField(blank=True, null=True, verbose_name='ISBN'),
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='作者'),
        ),
        migrations.AlterField(
            model_name='book',
            name='pub_date',
            field=models.DateField(blank=True, null=True, verbose_name='出版日期'),
        ),
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='出版社'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=200, unique=True, verbose_name='书名'),
        ),
        migrations.AddField(
            model_name='barcode',
            name='belong_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookshelf_app.Book'),
        ),
    ]
