# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-28 01:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf_app', '0002_auto_20170327_1116'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookID',
            fields=[
                ('book_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='barcode',
            name='belong_to',
        ),
        migrations.AlterField(
            model_name='book',
            name='CLC',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='分类号'),
        ),
        migrations.DeleteModel(
            name='BarCode',
        ),
        migrations.AddField(
            model_name='bookid',
            name='belong_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookshelf_app.Book'),
        ),
    ]
