# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-29 07:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf_app', '0004_auto_20170328_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='pub_date',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='出版日期'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(error_messages={'unique': '该书名已存在，请重新检查'}, max_length=200, unique=True, verbose_name='书名'),
        ),
    ]
