# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-30 01:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf_app', '0007_auto_20170329_1604'),
    ]

    operations = [
        migrations.CreateModel(
            name='LatelyBooksCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lately_books_count', models.IntegerField()),
                ('name', models.CharField(default='lately_books_count', max_length=200)),
            ],
        ),
    ]
