# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-31 00:50
from __future__ import unicode_literals

import bookshelf_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf_app', '0008_latelybookscount'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookid',
            name='is_lately_book',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='pub_date',
            field=models.IntegerField(blank=True, null=True, validators=[bookshelf_app.models.validate_pub_date], verbose_name='出版日期'),
        ),
    ]
