# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-31 01:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf_app', '0009_auto_20170331_0850'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LatelyBooksCount',
        ),
    ]
